#!/usr/bin/env node
/* ============================================================
   数据备份脚本（SQLite 迁移后：MySQL 版）
   位置：database/backup-db.cjs（数据库相关工具都放 database/）
   用法：node database/backup-db.cjs
   产物：database/backups/blog_backup_YYYYMMDD-HHMMSS.sql
        （仅 SQL，可直接导入 MySQL）
   说明：依赖从 backend/node_modules 引用；连接信息读 backend/.env
   ============================================================ */
const path = require('path');
const fs = require('fs');

// 从 backend/node_modules 加载依赖（database 目录本身不装 npm 包）
const BACKEND_NM = path.resolve(__dirname, '..', 'backend', 'node_modules');
const mysql = require(path.join(BACKEND_NM, 'mysql2/promise'));
const dotenv = require(path.join(BACKEND_NM, 'dotenv'));

// 读取 backend/.env
dotenv.config({ path: path.resolve(__dirname, '..', 'backend', '.env') });

const DB = {
  host: process.env.DB_HOST || '127.0.0.1',
  port: Number(process.env.DB_PORT || 3306),
  user: process.env.DB_USER || 'blog',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_NAME || 'blog_db',
};

const BACKUP_DIR = path.resolve(__dirname, 'backups');

const stamp = () => {
  const d = new Date();
  const p = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;
};

// MySQL 值转 SQL 字面量（安全转义）
const esc = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') {
    return Number.isFinite(v) ? String(v) : 'NULL';
  }
  if (v instanceof Date) {
    return `'${v.toISOString().slice(0, 19).replace('T', ' ')}'`;
  }
  const s = String(v).replace(/\\/g, '\\\\').replace(/'/g, "''");
  return `'${s}'`;
};

async function main() {
  console.log(`🔗 连接 ${DB.host}:${DB.port}/${DB.database} ...`);

  const conn = await mysql.createConnection({
    ...DB,
    charset: 'utf8mb4',
    // 时间保持数据库原始字符串，避免时区/格式错乱
    dateStrings: true,
  });

  // 所有业务表
  const [tablesRes] = await conn.query(
    "SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA = ? AND TABLE_TYPE = 'BASE TABLE'",
    [DB.database]
  );
  const tables = tablesRes.map((t) => t.TABLE_NAME);
  console.log(`📦 找到 ${tables.length} 张表: ${tables.join(', ')}`);

  const lines = [
    `-- Database backup: ${DB.database}`,
    `-- Exported at: ${new Date().toISOString()}`,
    `-- Generated by database/backup-db.cjs`,
    `-- DB: ${DB.host}:${DB.port}`,
    '', `USE \`${DB.database}\`;`, '',
  ];

  for (const table of tables) {
    const [colsRes] = await conn.query(`SHOW COLUMNS FROM \`${table}\``);
    const columns = colsRes.map((c) => c.Field);
    const colList = columns.map((c) => `\`${c}\``).join(', ');

    const [rowsRes] = await conn.query(`SELECT * FROM \`${table}\``);
    const rows = rowsRes.map((r) => columns.map((c) => r[c] ?? null));

    // 表结构（简化：DROP + CREATE）
    const [createRes] = await conn.query(`SHOW CREATE TABLE \`${table}\``);
    const createSql = createRes[0]['Create Table'];
    lines.push(`DROP TABLE IF EXISTS \`${table}\`;`);
    lines.push(createSql + ';');
    lines.push('');

    for (const row of rows) {
      lines.push(`INSERT INTO \`${table}\` (${colList}) VALUES (${row.map(esc).join(', ')});`);
    }
    if (rows.length) lines.push('');

    console.log(`  ✅ ${table}: ${rows.length} 行`);
  }

  await conn.end();

  if (!fs.existsSync(BACKUP_DIR)) fs.mkdirSync(BACKUP_DIR, { recursive: true });

  const file = path.join(BACKUP_DIR, `blog_backup_${stamp()}.sql`);
  fs.writeFileSync(file, lines.join('\n'));
  console.log(`\n✅ 备份完成: ${file}`);
}

main().catch((e) => {
  console.error('\n❌ 备份失败:', e);
  process.exit(1);
});